/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs_weatherforecast_MyLittleHelpers_Conversion */

#ifndef _Included_rtrk_pnrs_weatherforecast_MyLittleHelpers_Conversion
#define _Included_rtrk_pnrs_weatherforecast_MyLittleHelpers_Conversion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs_weatherforecast_MyLittleHelpers_Conversion
 * Method:    conversion
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_rtrk_pnrs_weatherforecast_MyLittleHelpers_Conversion_conversion
  (JNIEnv *, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
